#!/usr/bin/env python3
"""本地会话可见文本投影；只使用标准库，原始源始终只读。"""
import argparse
from collections import Counter
from datetime import date, datetime, timedelta, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import sys
import tempfile

OWNER = "import_local_ai_sessions/v1"
MARKER = "<!-- generated by " + OWNER + " -->"
SOURCES = ("pi", "codex", "claude", "claudian", "chatgpt")
SECRET = r"(?:[\w.-]*(?:api[_-]?key|access[_-]?token|refresh[_-]?token|token|password|passwd|secret|authorization|cookie)[\w.-]*)"
PAIR = re.compile(r'(?i)([\"\']?\b' + SECRET + r'[\"\']?\s*[:=]\s*)(\[REDACTED: [^\]\r\n]+\]|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|[^\s,;}]+)')
HEADER = re.compile(r"(?im)^(\s*(?:authorization|proxy-authorization|cookie|set-cookie)\s*:\s*).+$")


def redact(text):
    text = str(text)
    text = re.sub(r"(?i)\bBearer\s+[A-Za-z0-9._~+/=-]+", "Bearer [REDACTED: token]", text)
    text = PAIR.sub(lambda m: m[0] if m[2].startswith("[REDACTED:") else m[1] + ('"[REDACTED: credential]"' if m[2].startswith('"') else "[REDACTED: credential]"), text)
    text = HEADER.sub(lambda m: m[1] + "[REDACTED: header]", text)
    text = re.sub(r"(?i)(--(?:api-key|token|password|secret)\s+)(\"[^\"]*\"|'[^']*'|\S+)", r"\1[REDACTED: credential]", text)
    text = re.sub(r"-----BEGIN (?:[A-Z ]* )?PRIVATE KEY-----.*?-----END (?:[A-Z ]* )?PRIVATE KEY-----", "[REDACTED: private-key]", text, flags=re.S)
    text = re.sub(r"\b(?:sk-[A-Za-z0-9_-]{12,}|gh[pousr]_[A-Za-z0-9]{20,}|AIza[A-Za-z0-9_-]{30,})\b", "[REDACTED: api-key]", text)
    text = re.sub(r"\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b", "[REDACTED: jwt]", text)
    return re.sub(r"(\w+://[^\s/:]+:)[^\s/@]+(@)", r"\1[REDACTED: password]\2", text)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def dumps(obj):
    return json.dumps(obj, ensure_ascii=False, indent=2)


def stamp(value):
    try:
        if isinstance(value, (int, float)):
            return datetime.fromtimestamp(value / 1000 if value > 1e11 else value, timezone.utc)
        if isinstance(value, str) and value:
            d = datetime.fromisoformat(value.replace("Z", "+00:00"))
            return d.replace(tzinfo=timezone.utc) if d.tzinfo is None else d.astimezone(timezone.utc)
    except (ValueError, OverflowError, OSError):
        pass
    return None


def visible(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(t for part in content if (t := visible(part)))
    if isinstance(content, dict):
        if content.get("type", "text") not in ("text", "input_text", "output_text"):
            return ""
        for key in ("text", "parts", "content"):
            if key in content:
                return visible(content[key])
    return ""


def message_parts(msg, tools=False, system=False):
    role = msg.get("role")
    if role is None and isinstance(msg.get("author"), dict):
        role = msg["author"].get("role")
    if msg.get("channel") in ("analysis", "thinking"):
        return []
    allowed = ("user", "assistant") + (("system", "developer") if system else ())
    if tools:
        allowed += ("tool", "toolResult", "tool_result")
    if role not in allowed:
        return []
    content = msg.get("content", msg.get("text", ""))
    result = []
    # 分块处理，保留文本与工具块在消息内的相对顺序。
    for part in content if isinstance(content, list) else [content]:
        text = visible(part)
        kind = role
        if tools and isinstance(part, dict):
            if part.get("type") in ("toolCall", "tool_use", "tool_call"):
                text = str(part.get("name", "")) + "\n" + dumps(part.get("arguments", part.get("input", {})))
                kind = "tool-call"
            elif part.get("type") == "tool_result":
                text = visible(part.get("content", ""))
                kind = "tool-result"
        if text:
            if result and result[-1][0] == kind and kind not in ("tool-call", "tool-result"):
                result[-1] = (kind, result[-1][1] + "\n" + redact(text))
            else:
                result.append((kind, redact(text)))
    return result


def parse_jsonl(raw, source, tools, system, report):
    messages, times, identity, title = [], [], None, ""
    for number, line in enumerate(raw.decode("utf-8-sig").splitlines(), 1):
        if not line.strip():
            continue
        try:
            ev = json.loads(line)
        except ValueError:
            report("invalid_json_line", line=number)
            continue
        if not isinstance(ev, dict):
            continue
        p = ev.get("payload") if isinstance(ev.get("payload"), dict) else ev
        for obj in (ev, p):
            t = stamp(obj.get("timestamp"))
            if t:
                times.append(t)
        typ = ev.get("type")
        if typ in ("session", "session_meta"):
            identity = identity or p.get("id") or p.get("session_id")
        identity = identity or ev.get("sessionId") or ev.get("session_id")
        if typ == "session_info":
            title = ev.get("name", "")
        if typ == "response_item":
            msg = p
        elif isinstance(ev.get("message"), dict):
            msg = ev["message"]
        elif typ == "message" or ev.get("role") or typ in ("user", "assistant"):
            msg = dict(p)
            msg.setdefault("role", typ if typ in ("user", "assistant") else None)
        else:
            continue
        t = stamp(msg.get("timestamp"))
        if t:
            times.append(t)
        if tools and msg.get("type") in ("function_call", "custom_tool_call", "function_call_output", "custom_tool_call_output"):
            is_result = msg["type"].endswith("output")
            text = msg.get("output", "") if is_result else str(msg.get("name", "")) + "\n" + str(msg.get("arguments", msg.get("input", "")))
            messages.append(("tool-result" if is_result else "tool-call", redact(text)))
        else:
            messages.extend(message_parts(msg, tools, system))
    return [{"id": identity, "title": title, "messages": messages, "times": times}]


def web_messages(node):
    """只接受带显式角色的正文；诊断、凭证及推理子树不遍历。"""
    result = []
    if isinstance(node, list):
        for item in node:
            result.extend(web_messages(item))
    elif isinstance(node, dict):
        if node.get("type") not in (None, "message", "user", "assistant"):
            return []
        if node.get("channel") in ("analysis", "reasoning", "thinking", "diagnostic", "log"):
            return []
        if isinstance(node.get("message"), dict):
            # 先解包事件；外层角色只能补缺，不能覆盖内层或放行系统消息。
            msg = dict(node["message"])
            outer_role = node.get("role")
            inner_role = msg.get("role")
            if inner_role is None and isinstance(msg.get("author"), dict):
                inner_role = msg["author"].get("role")
            if outer_role is not None:
                if outer_role not in ("user", "assistant") or inner_role not in (None, outer_role):
                    return []
                msg.setdefault("role", outer_role)
            return web_messages(msg)
        if node.get("role") or isinstance(node.get("author"), dict):
            return message_parts(node)
        if isinstance(node.get("mapping"), dict):
            # Web 树必须有活动叶节点，不能把字典顺序伪装成会话顺序。
            mapping, current, chain, seen = node["mapping"], node.get("current_node"), [], set()
            if not current:
                return []
            while current:
                if current in seen or current not in mapping or not isinstance(mapping[current], dict):
                    return []
                seen.add(current)
                chain.append(mapping[current].get("message"))
                current = mapping[current].get("parent")
            return web_messages(list(reversed(chain)))
        # 白名单遍历结构字段，不搜索任意子树中的“像消息”数据。
        for key in ("items", "messages", "conversation"):
            if key in node:
                result.extend(web_messages(node[key]))
    return result


def parse_web(data):
    if not isinstance(data, (dict, list)):
        return []
    root = data
    if isinstance(root, dict):
        for key in ("states", "responses", "conversations"):
            if isinstance(root.get(key), (dict, list)):
                root = root[key]
                break
    if isinstance(root, dict) and any(k in root for k in ("items", "messages", "mapping", "conversation")):
        entries = [(root.get("id") or root.get("state_id"), root)]
    elif isinstance(root, dict):
        entries = list(root.items())
    else:
        entries = [(v[0], v[1]) if isinstance(v, list) and len(v) == 2 and isinstance(v[0], str)
                   else (None, v) for v in root]
    result = []
    for key, obj in entries:
        if not isinstance(obj, dict):
            continue
        identity = key or obj.get("state_id") or obj.get("id")
        if not identity:
            continue
        created = stamp(obj.get("createdAt"))
        times = [created] if created else [t for k in ("created_at", "updated_at", "create_time", "update_time", "timestamp") if (t := stamp(obj.get(k)))]
        result.append({"id": identity, "title": obj.get("title", ""), "times": times, "messages": web_messages(obj)})
    return result


def safe_title(text):
    return re.sub(r'[\x00-\x1f<>:"/\\|?*\[\]#]', " ", redact(text)).strip(" .")[:100] or "Untitled"


def topics(text):
    groups = {"编程": ("code", "python", "bug", "代码", "编程", "测试"), "写作": ("写作", "小说", "writing"), "学习": ("学习", "数学", "learn"), "AI与归档": ("agent", "模型", "归档", "obsidian")}
    return [name for name, words in groups.items() if any(w in text.lower() for w in words)] or ["未分类"]


def blocked(path):
    return any(re.search(r"\.bak|\.corrupted|^auth\.|^settings\.|^\.env", p, re.I) for p in path.parts)


def discover(root, pattern, report):
    if blocked(root):
        report("excluded_sensitive_or_backup_path")
        return []
    if not root.exists():
        report("source_missing")
        return []
    if root.is_symlink():
        report("symlink_source_skipped")
        return []
    if root.is_file():
        if not root.match(pattern):
            report("unsupported_source_filename")
            return []
        return [root]
    found = []
    def error(exc):
        report("scan_error", error=type(exc).__name__)
    for directory, dirs, files in os.walk(root, onerror=error, followlinks=False):
        dirs[:] = [d for d in dirs if not blocked(Path(d)) and not Path(directory, d).is_symlink()]
        for name in sorted(files):
            p = Path(directory, name)
            if p.match(pattern) and not blocked(p) and not p.is_symlink():
                found.append(p)
    return sorted(found)


def output_path(root, relative):
    p = root / relative
    if p.is_symlink() or not p.resolve().is_relative_to(root.resolve()):
        raise ValueError("unsafe_output_path")
    return p


def write_owned(root, relative, text, previous_hash=None):
    p = output_path(root, relative)
    if p.exists():
        if not previous_hash or digest(p.read_bytes()) != previous_hash:
            raise ValueError("existing_or_modified_file")
    p.parent.mkdir(parents=True, exist_ok=True)
    # 临时文件和目标在同一卷，替换为原子操作。
    fd, name = tempfile.mkstemp(prefix=".import-", dir=p.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
        os.replace(name, p)
    finally:
        if os.path.exists(name):
            os.unlink(name)


def run(args):
    root = args.output_dir.resolve()
    now = datetime.now(timezone.utc).isoformat()
    manifest_path = output_path(root, "manifest.json")
    old = {"files": [], "generated_files": {}}
    manifest_hash = None
    if manifest_path.exists():
        old = json.loads(manifest_path.read_text(encoding="utf-8"))
        if old.get("generator") != OWNER:
            raise ValueError("manifest_not_owned")
        manifest_hash = digest(manifest_path.read_bytes())
    files = {f["identity_key"]: f for f in old["files"]}
    skipped, inventory, counts = [], [], Counter()
    def skip(source, path, reason, **details):
        skipped.append(dict(source=source, source_file=redact(str(path)), skipped_reason=reason, **details))
    specs = [("pi", args.pi_dir, "*.jsonl"), ("codex", args.codex_dir, "*.jsonl"), ("codex", args.codex_archived_dir, "*.jsonl"), ("claude", args.claude_dir, "*.jsonl"), ("claudian", args.claudian_dir, "*.meta.json"), ("chatgpt", args.chatgpt_state, "responses-state.json")]
    candidates = []
    for source, directory, pattern in specs:
        if args.source not in ("all", source):
            continue
        try:
            paths = discover(directory, pattern, lambda reason, **kw: skip(source, directory, reason, **kw))
        except OSError as exc:
            skip(source, directory, "scan_error", error=type(exc).__name__)
            paths = []
        inventory.append({"source": source, "root": redact(str(directory)), "discovered_files": len(paths)})
        for path in paths:
            try:
                raw = path.read_bytes()
                sha = digest(raw)
                report = lambda reason, **kw: skip(source, path, reason, **kw)
                before = len(skipped)
                if source == "claudian":
                    obj = json.loads(raw.decode("utf-8-sig"))
                    if not isinstance(obj, dict):
                        raise ValueError("invalid_metadata")
                    sessions = [{"id": obj.get("sessionId") or obj.get("id") or path.name.removesuffix(".meta.json"), "title": obj.get("title", ""), "messages": [], "times": [t for k in ("createdAt", "updatedAt", "created_at", "updated_at", "lastModified") if (t := stamp(obj.get(k)))]}]
                elif source == "chatgpt":
                    sessions = parse_web(json.loads(raw.decode("utf-8-sig")))
                else:
                    sessions = parse_jsonl(raw, source, args.include_tools, args.include_system, report)
                if not sessions:
                    report("no_reliable_messages_or_state_id")
                for session in sessions:
                    session.update(source=source, path=path, sha=sha, partial=len(skipped) > before)
                    if not session["messages"] and source != "claudian":
                        report("no_reliable_visible_messages", state_id=redact(session.get("id") or ""))
                        continue
                    times = session["times"]
                    session["date_basis"] = "source_timestamp" if times else "file_mtime"
                    session["start"] = min(times) if times else datetime.fromtimestamp(path.stat().st_mtime, timezone.utc)
                    session["end"] = max(times) if times else session["start"]
                    if session["end"].date() < args.since:
                        report("before_since")
                        continue
                    candidates.append(session)
            except (OSError, ValueError, TypeError, RecursionError) as exc:
                skip(source, path, "read_or_parse_error", error=type(exc).__name__)
    # 相同身份的多个快照选最新；同一文件的 web states 不按文件 hash 合并。
    seen_hash = {}
    for item in old["files"]:
        for sha in item.get("source_hashes", [item["source_sha256"]]):
            seen_hash[(item["source"], sha)] = item["identity_key"]
    processed = set()
    for s in sorted(candidates, key=lambda x: (x["end"], len(x["messages"])), reverse=True):
        source, sha = s["source"], s["sha"]
        sid = str(s["id"] or sha)
        key = source + ":" + digest(sid.encode("utf-8"))
        prior = files.get(key)
        if prior and s["end"] < stamp(prior["updated_at"]):
            counts["older_snapshots"] += 1
            continue
        if source != "chatgpt" and (source, sha) in seen_hash and seen_hash[(source, sha)] != key:
            counts["duplicates"] += 1
            continue
        if key in processed:
            counts["duplicates"] += 1
            continue
        processed.add(key)
        title = safe_title(s["title"] or next((text for role, text in s["messages"] if role == "user"), sid))
        status = "metadata-only" if source == "claudian" else "partial-visible-text" if s["partial"] else "visible-text"
        body = "\n\n".join("## " + role + "\n\n" + text for role, text in s["messages"])
        content_hash = digest(body.encode("utf-8"))
        relative = prior["path"] if prior else "by-date/" + s["start"].strftime("%Y/%m/%d/") + source + "-" + key.split(":")[1][:24] + ".md"
        entry = dict(source=source, session_id=redact(sid), started_at=s["start"].isoformat(), updated_at=s["end"].isoformat(), imported_at=prior["imported_at"] if prior else now, message_count=len(s["messages"]), source_file=redact(str(s["path"])), content_status=status, content_sha256=content_hash, source_sha256=sha, date_basis=s["date_basis"], title=title, topic_method="heuristic", topics=topics(title), generator=OWNER)
        front = "---\n" + "\n".join(k + ": " + json.dumps(v, ensure_ascii=False) for k, v in entry.items()) + "\n---\n"
        text = front + MARKER + "\n# " + title + "\n\n> 自动生成的可见文本投影；已做凭证脱敏。Pi 按记录顺序包含各分支；未重建活动分支。\n\n"
        text += ("> metadata-only：源仅含元数据，没有可验证的会话正文。\n" if status == "metadata-only" else body + "\n")
        entry.update(identity_key=key, path=relative, output_sha256=digest(text.encode("utf-8")), source_hashes=sorted(set((prior or {}).get("source_hashes", []) + [sha])))
        try:
            p = output_path(root, relative)
            if p.exists() and (not prior or digest(p.read_bytes()) != prior["output_sha256"]):
                raise ValueError("existing_or_modified_file")
            unchanged = prior and entry["output_sha256"] == prior["output_sha256"] and p.exists()
            if not unchanged and not args.dry_run:
                write_owned(root, relative, text, prior["output_sha256"] if prior else None)
            files[key] = entry
            seen_hash[(source, sha)] = key
            counts["unchanged" if unchanged else "updated" if prior else "created"] += 1
        except (OSError, ValueError) as exc:
            skip(source, s["path"], str(exc) if isinstance(exc, ValueError) else "write_error")
    rows = sorted(files.values(), key=lambda f: (f["started_at"], f["path"]), reverse=True)
    def link(f):
        return "- [" + f["started_at"][:10] + " · " + f["title"] + "](" + f["path"] + ") · " + f["content_status"]
    time_index = MARKER + "\n# 按时间\n\n" + "\n".join(map(link, rows)) + "\n"
    topic_index = MARKER + "\n# 按来源与主题\n\n主题为 heuristic：仅匹配标题或首条用户消息的关键词，不调用模型。\n"
    for source in SOURCES:
        group = [f for f in rows if f["source"] == source]
        if group:
            topic_index += "\n## " + source + "\n"
            for topic in sorted({t for f in group for t in f["topics"]}):
                topic_index += "\n### " + topic + "\n\n" + "\n".join(link(f) for f in group if topic in f["topics"]) + "\n"
    generated = dict(old.get("generated_files", {}))
    for name, text in (("按时间.md", time_index), ("按来源与主题.md", topic_index)):
        try:
            p = output_path(root, name)
            if p.exists() and digest(p.read_bytes()) != generated.get(name):
                raise ValueError("existing_or_modified_file")
            if not args.dry_run:
                write_owned(root, name, text, generated.get(name))
            generated[name] = digest(text.encode("utf-8"))
        except (OSError, ValueError):
            skip("index", name, "existing_modified_or_unwritable_index")
    counts.update({"total_archived": len(rows), "skipped": len(skipped)})
    manifest = dict(generator=OWNER, imported_at=now, since=args.since.isoformat(), counts=dict(counts), skipped=skipped, files=rows, source_inventory=inventory, generated_files=generated)
    if not args.dry_run:
        write_owned(root, "manifest.json", dumps(manifest) + "\n", manifest_hash)
    return manifest


def parser():
    home = Path.home()
    project = Path(__file__).resolve().parent.parent
    vault = project.parent.parent
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--source", choices=("all",) + SOURCES, default="all")
    p.add_argument("--since", type=date.fromisoformat, default=date.today() - timedelta(days=365))
    p.add_argument("--output-dir", type=Path, default=project / "_auto-import", help="专用自动生成目录，默认当前项目/_auto-import")
    for flag in ("dry-run", "include-tools", "include-system", "check"):
        p.add_argument("--" + flag, action="store_true")
    for flag, default in (("pi-dir", home / ".pi/agent/sessions"), ("codex-dir", home / ".codex/sessions"), ("codex-archived-dir", home / ".codex/archived_sessions"), ("claude-dir", home / ".claude/projects"), ("claudian-dir", vault / ".claudian/sessions"), ("chatgpt-state", home / ".codex-chatgpt-web/responses-state.json")):
        p.add_argument("--" + flag, type=Path, default=default)
    return p


def main():
    args = parser().parse_args()
    if args.check:
        import unittest
        suite = unittest.defaultTestLoader.discover(str(Path(__file__).parent), pattern="test_import_local_ai_sessions.py")
        return 0 if unittest.TextTestRunner(verbosity=2).run(suite).wasSuccessful() else 1
    try:
        result = run(args)
        print(dumps({"dry_run": args.dry_run, "counts": result["counts"], "source_inventory": result["source_inventory"], "skipped": result["skipped"], "planned_files": [f["path"] for f in result["files"]]}))
        return 0
    except (OSError, ValueError, KeyError) as exc:
        print("Import failed: " + redact(str(exc)), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
